FROM node:10.16.3

WORKDIR /opt/builder

COPY ./context ./

RUN apt-get update && \
    apt-get -y install git unzip build-essential autoconf libtool

RUN git clone https://github.com/google/protobuf.git && \
    cd protobuf && \
    ./autogen.sh && \
    ./configure && \
    make && \
    make install && \
    ldconfig && \
    make clean && \
    cd .. && \
    rm -r protobuf

RUN npm i typescript -g --unsafe-perm --loglevel verbose && \
    npm i grpc-tools -g --unsafe-perm --loglevel verbose && \
    npm i yarn -g  --unsafe-perm --loglevel verbose && \
    which protoc && protoc --version && \
    which tsc && tsc --version && \
    which grpc_tools_node_protoc && grpc_tools_node_protoc --version && \
    npm list -g --depth=0 | grep grpc-tools

