kind: pipeline
type: exec
name: test

platform:
  os: darwin
  arch: amd64

steps:
  - name: test
    commands:
      - /bin/bash bash/unit.sh
    when:
      event:
        - tag

---
kind: pipeline
type: exec
name: build

platform:
  os: darwin
  arch: amd64

steps:
  - name: build
    commands:
      - /bin/bash bash/docker.sh
    when:
      event:
        - tag

depends_on:
  - test
